# -*- coding: utf-8 -*-
"""While Loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMvvt3NtyiNFjCQbEWZ0SndKO9wnm2hv
"""

#write a while loop repeating * sequienttialy till 5
x = 1
while x <= 5:
  print("*" * x)
  x = x + 1